require: 
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'db/**/*'
    - 'bin/**/*'
    - 'Gemfile'
    - 'Gemfile.lock'
    - 'Rakefile'
    - 'Guardfile'
    - 'node_modules/**/*'
    - 'config/**/*'
    - 'tmp/**/*'
    - '*.ru'
    - 'Dangerfile'
  TargetRubyVersion: 2.7
  NewCops: enable
Rails/I18nLocaleTexts:
  Enabled: false

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 120
  Exclude:
    - 'spec/**/*'
    - 'config/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Style/FormatStringToken:
  EnforcedStyle: template

Rails/FilePath:
  EnforcedStyle: arguments

RSpec/HookArgument:
  EnforcedStyle: each

RSpec/ContextWording:
  Prefixes:
    - when
    - given