version: '3.2'

services:
  db:
    image: postgres:12.1
    container_name: challenge_db
    environment:
      - POSTGRES_DB=challenge_test
    ports:
      - "5432:5432"

  redis:
    image: redis:5.0.7
    container_name: challenge_redis
    ports:
      - "6379:6379"

volumes:
  ruby-bundle: